[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python3 bot.py"
healthcheckPath = "/health"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 20 