[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"
buildpacks = ["https://github.com/heroku/heroku-buildpack-ffmpeg.git"]

[deploy]
startCommand = "python bot.py"
healthcheckPath = ""
healthcheckTimeout = 0
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10 